name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  dev:
    if: contains(github.event.base_ref, 'feature')
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            cdk/**
            !cdk/.venv
            !cdk/cdk.out

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: CDK
        run: |
          sudo npm install -g aws-cdk
          cd cdk
          pip install --upgrade -r requirements.txt
          cdk deploy --require-approval never --all
        shell: bash
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_TARGET_ACCOUNT: 227957190059


  uat:
    # Only runs once approval and upload have occurred - Environment needs 1 or more reviewer(s)!
    needs: dev
    runs-on: ubuntu-latest
    environment:
      name: uat

    steps:
      - name: Download package
        uses: actions/download-artifact@v2

      - name: Bash
        run: |
          cd artifact
          ls | while read i; do echo filename: $i; done

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: CDK
        run: |
          cd artifact
          sudo npm install -g aws-cdk
          cd cdk
          pip install --upgrade -r requirements.txt
          cdk deploy --require-approval never --all
        shell: bash
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_TARGET_ACCOUNT: 897994618109
