# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the feature branches
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # Allows for approval
          draft: true
          prerelease: false

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "."

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "."
          asset_content_type: application/zip
                    
  uat:
    # Only runs once approval and upload have occurred
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: uat

    steps:
      - name: Download package
        uses: actions/download-artifact@v2
